version: '3.8'

services:
  age-prediction-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: age-prediction-backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HUGGINGFACE_MODEL_REPO=Sanjayramdata/celingfan
    restart: unless-stopped
